### ISSUE TITLE
No such file or directory @ rb_sysopen - actions.yml

### ISSUE THREAD

**Issue by rgrabowski** [amgencjana/magic_matrix#2]
```
ActionView::Template::Error (No such file or directory @ rb_sysopen - actions.yml):
    21:               <div class="col-xs-4">
    22:                 <div class="form-group">
    23:                   <%= f.label :event_type %>
    24:                   <%= f.select :event_type, options_for_select(Magic::Matrix.new( 'actions.yml' ).matrix), {}, class: 'form-control' %>
    25:                 </div>
    26:               </div>
    27: 
  /Users/rafalgrabowski/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:471:in `initialize'
  /Users/rafalgrabowski/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:471:in `open'
  /Users/rafalgrabowski/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:471:in `load_file'
  /Users/rafalgrabowski/Projects/github_clones/magic_matrix/lib/magic_matrix/matrix.rb:14:in `initialize'
  /Users/rafalgrabowski/Projects/github_clones/sales_api/app/views/sales_api/calendars/_new_next_action.html.erb:24:in `new'
  /Users/rafalgrabowski/Projects/github_clones/sales_api/app/views/sales_api/calendars/_new_next_action.html.erb:24:in `block in ___sers_rafalgrabowski__rojects_github_clones_sales_api_app_views_sales_api_calendars__new_next_action_html_erb___1465430950112072466_70129145173940'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.6) lib/action_view/helpers/form_helper.rb:444:in `form_for'
  /Users/rafalgrabowski/Projects/github_clones/sales_api/app/views/sales_api/calendars/_new_next_action.html.erb:11:in `___sers_rafalgrabowski__rojects_github_clones_sales_api_app_views_sales_api_calendars__new_next_action_html_erb___1465430950112072466_70129145173940'
  actionview (4.2.6) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.6) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.6) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.6) lib/action_view/template.rb:143:in `render'
  actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:339:in `render_p
```

**Comment by amgencjana** [comment]
@rgrabowski usage of this library allows you to 'navigate' through the hash 
so based on the any i.e. actions.yaml file, content for: 
options_for_select() can be build
